package br.com.forumhub.domain.curso;

public enum Categoria {
    ARQUITETURA_DE_SISTEMAS,
    BACKEND,
    BANCO_DE_DADOS,
    CIENCIA_DE_DADOS,
    CLOUD_COMPUTING,
    CYBERSECURITY,
    DESENVOLVIMENTO_MOBILE,
    DEVOPS,
    ENGENHARIA_DE_SOFTWARE,
    FRONTEND,
    GOVERNANCA_E_GESTAO_TI,
    HARDWARE_E_IOT,
    INTELIGENCIA_ARTIFICIAL,
    REDES_E_INFRAESTRUTURA,
    SEGURANCA_DA_INFORMACAO,
    SOFTSKILLS,
    TESTES_E_QUALIDADE,
    UX_UI_DESIGN
}
